In [1]:
import pandas as pd

In [20]:
df = pd.read_csv("Climate_Search_All_Dates.csv")

In [21]:
df

,STATION,NAME,DATE,DAPR,DASF,MDPR,MDSF,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESD,WESF,WT01,WT03,WT05,WT11
0,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-24,NaN,NaN,NaN,NaN,0.57,0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-25,NaN,NaN,NaN,NaN,0.08,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-26,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-27,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-28,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-29,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-30,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-05-31,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-01,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-02,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-03,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-05,NaN,NaN,NaN,NaN,0.38,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-06,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-07,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-08,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-09,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-10,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-11,NaN,NaN,NaN,NaN,0.02,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-12,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-13,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-14,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-15,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-16,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-17,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-18,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-19,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-20,NaN,NaN,NaN,NaN,0.25,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-21,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-22,NaN,NaN,NaN,NaN,0.23,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,US1COAR0061,"CHERRY CREEK DAM 2.7 ESE, CO US",2002-06-23,NaN,NaN,NaN,NaN,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166,US1COAR0207,"AURORA 7.3 SE, CO US",2020-05-29,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15167,US1COAR0207,"AURORA 7.3 SE, CO US",2020-05-30,NaN,NaN,NaN,NaN,0.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15168,US1COAR0207,"AURORA 7.3 SE, CO US",2020-05-31,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15169,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-01,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15170,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-02,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15171,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-03,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15172,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-04,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15173,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-05,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15174,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-06,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15175,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-07,NaN,NaN,NaN,NaN,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15176,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-08,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15177,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-09,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15178,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-10,NaN,NaN,NaN,NaN,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15179,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-11,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15180,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-12,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15181,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-13,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15182,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-14,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15183,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-15,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15184,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-16,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15185,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-17,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15186,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-18,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15187,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-19,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15188,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-20,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15189,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-21,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15190,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-23,NaN,NaN,NaN,NaN,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15191,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-24,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15192,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-25,NaN,NaN,NaN,NaN,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15193,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-26,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15194,US1COAR0207,"AURORA 7.3 SE, CO US",2020-06-27,NaN,NaN,NaN,NaN,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15195,US1COAR0207,"AURORA 7.3 SE, CO US",2020-07-05,NaN,NaN,NaN,NaN,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
new_df = df[['PRCP', 'SNOW', 'SNWD']].copy()

In [28]:
new_df

       PRCP  SNOW  SNWD
0      0.57   0.5   0.0
1      0.08   0.0   0.0
2      0.00   0.0   0.0
3      0.00   0.0   0.0
4      0.00   0.0   0.0
5      0.00   0.0   0.0
6      0.00   0.0   0.0
7      0.00   0.0   0.0
8      0.00   0.0   0.0
9      0.00   0.0   0.0
10     0.00   0.0   0.0
11     0.38   0.0   0.0
12     0.00   0.0   0.0
13     0.00   0.0   0.0
14     0.00   0.0   0.0
15     0.00   0.0   0.0
16     0.00   0.0   0.0
17     0.02   0.0   0.0
18     0.00   0.0   0.0
19     0.00   0.0   0.0
20     0.00   0.0   0.0
21     0.00   0.0   0.0
22     0.00   0.0   0.0
23     0.00   0.0   0.0
24     0.00   0.0   0.0
25     0.00   0.0   0.0
26     0.25   0.0   0.0
27     0.00   0.0   0.0
28     0.23   0.0   0.0
29     0.00   0.0   0.0
...     ...   ...   ...
15166  0.00   0.0   NaN
15167  0.29   NaN   NaN
15168  0.00   0.0   NaN
15169  0.00   0.0   NaN
15170  0.00   0.0   NaN
15171  0.00   0.0   NaN
15172  0.00   0.0   NaN
15173  0.00   0.0   NaN
15174  0.00   0.0   NaN
15175  0.28   NaN   NaN
15176  0.00   0.0   NaN
15177  0.69   NaN   NaN
15178  0.02   NaN   NaN
15179  0.00   0.0   NaN
15180  0.00   0.0   NaN
15181  0.01   NaN   NaN
15182  0.01   NaN   NaN
15183  0.00   0.0   NaN
15184  0.00   0.0   NaN
15185  0.00   0.0   NaN
15186  0.00   0.0   NaN
15187  0.00   NaN   NaN
15188  0.01   NaN   NaN
15189  0.00   0.0   NaN
15190  0.02   NaN   NaN
15191  0.00   0.0   NaN
15192  0.02   NaN   NaN
15193  0.00   0.0   NaN
15194  0.02   NaN   NaN
15195  0.98   NaN   NaN

[15196 rows x 3 columns]

In [29]:
new_df.isnull().values.any()

True

In [30]:
len(new_df.dropna())

7586

In [11]:
df = pd.read_csv("Precipitation_All_Dates.csv")

In [12]:
df

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,HPCP,Measurement Flag,Quality Flag
0,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19970919 19:00,0.20,,
1,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19970920 14:00,0.20,,
2,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19970923 00:00,0.10,,
3,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19970923 01:00,0.10,,
4,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971001 01:00,0.00,g,
5,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971011 04:00,0.10,,
6,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971011 05:00,0.10,,
7,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971011 06:00,0.10,,
8,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971011 11:00,0.20,,
9,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971023 08:00,0.10,,
10,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971023 23:00,0.10,,
11,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971025 13:00,0.10,,
12,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971025 14:00,0.20,,
13,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971030 05:00,999.99,{,
14,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971031 13:00,999.99,},
15,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971031 14:00,999.99,[,
16,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971101 00:00,999.99,],
17,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971101 01:00,0.00,g,
18,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971110 13:00,0.10,,
19,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971110 14:00,0.10,,
20,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971112 10:00,0.10,,
21,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971112 14:00,0.10,,
22,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971126 16:00,0.10,,
23,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 01:00,0.10,,
24,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 12:00,0.10,,
25,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 13:00,0.10,,
26,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 14:00,0.10,,
27,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 15:00,0.10,,
28,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 16:00,0.10,,
29,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.62611,-104.83194,19971128 19:00,0.10,,
...,...,...,...,...,...,...,...,...,...
1153,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060708 14:00,0.10,,
1154,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 04:00,0.10,,
1155,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 06:00,0.20,,
1156,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 07:00,0.10,,
1157,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 12:00,0.10,,
1158,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 14:00,0.10,,
1159,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060709 23:00,0.10,,
1160,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060726 13:00,0.10,,
1161,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060801 01:00,0.00,g,
1162,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060801 15:00,0.30,,
1163,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060801 16:00,0.30,,
1164,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060803 09:00,999.99,{,
1165,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060803 12:00,999.99,},
1166,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060803 18:00,0.10,,
1167,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060805 21:00,0.10,,
1168,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060806 14:00,0.10,,
1169,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060806 20:00,0.10,,
1170,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060812 19:00,0.10,,
1171,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060813 20:00,0.20,,
1172,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060813 21:00,0.10,,
1173,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060816 22:00,0.10,,
1174,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060819 08:00,0.30,,
1175,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060819 18:00,0.10,,
1176,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060825 15:00,0.10,,
1177,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060826 08:00,0.10,,
1178,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060826 23:00,0.10,,
1179,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060901 01:00,0.00,g,
1180,COOP:051547,CHERRY CREEK DAM CO US,1721.2,39.6261,-104.8319,20060904 14:00,999.99,[,
1181,COOP:051547,CHERRY CREEK DAM CO US,unknown,unknown,unknown,20061001 00:00,999.99,],
1182,COOP:051547,CHERRY CREEK DAM CO US,unknown,unknown,unknown,20061001 01:00,999.99,[,

In [13]:
NaN_counter = 0
for index, row in df.iterrows():
    if row['HPCP'] == 999.99:
        NaN_counter = NaN_counter + 1

In [14]:
NaN_counter

157

In [15]:
len(df.index)

1183

In [17]:
non_NaN_count = len(df.index) - NaN_counter
non_NaN_count

1026

In [15]:
df1 = pd.read_csv("NOAA_80015_2020.csv")

In [19]:
len(df1.STATION.unique())

2

In [20]:
df1.STATION.unique()

array(['US1COAR0367', 'US1COAR0207'], dtype=object)

In [21]:
df2 = pd.read_csv("NOAA_80221_2020.csv")

In [22]:
len(df2.STATION.unique())

1

In [23]:
df2.STATION.unique()

array(['US1COAD0231'], dtype=object)

# Examine zipcodes from NBI Colorado 2019 and see how many bridges are in 80015 and 80221 respectively

In [2]:
df = pd.read_csv("NBI_Colorado_zipcodes.csv")

In [3]:
df

      Unnamed: 0           0
0              0       81220
1              1       81220
2              2         NaN
3              3         NaN
4              4         NaN
5              5         NaN
6              6         NaN
7              7       81136
8              8         NaN
9              9       81321
10            10       81327
11            11       81327
12            12       81327
13            13       81327
14            14         NaN
15            15         NaN
16            16         NaN
17            17       81301
18            18       81327
19            19  81328-9151
20            20       81301
21            21       81327
22            22         NaN
23            23         NaN
24            24         NaN
25            25         NaN
26            26         NaN
27            27         NaN
28            28         NaN
29            29       80446
...          ...         ...
8732        8732       80807
8733        8733       80735
8734        8734         NaN
8735        8735       80758
8736        8736         NaN
8737        8737       80735
8738        8738       80824
8739        8739       80735
8740        8740       80759
8741        8741       80759
8742        8742       80735
8743        8743         NaN
8744        8744         NaN
8745        8745       80822
8746        8746       80758
8747        8747       80758
8748        8748       80758
8749        8749       80758
8750        8750       80735
8751        8751       80735
8752        8752         NaN
8753        8753       80822
8754        8754       80758
8755        8755         NaN
8756        8756         NaN
8757        8757         NaN
8758        8758       80824
8759        8759       80824
8760        8760       80807
8761        8761       80807

[8762 rows x 2 columns]

In [14]:
count = 0
for i, row in df.iterrows():
    if row["0"] == "80015":
        count += 1
        
print("For the year 2019 for Colorado in NBI, there are " + str(count) + " bridges within 80015")

For the year 2019 for Colorado in NBI, there are 10 bridges within 80015

In [15]:
count = 0
for i, row in df.iterrows():
    if row["0"] == "80221":
        count += 1
        
print("For the year 2019 for Colorado in NBI, there are " + str(count) + " bridges within 80221")

For the year 2019 for Colorado in NBI, there are 30 bridges within 80221